fastlane_version '2.157'
default_platform :ios

# Set environment variables globally to handle xcodebuild timeouts
ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '60'
ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = '2'

platform :ios do

    desc 'Builds project and executes unit tests'
    lane :unit_test do |options|
        scan(
            clean: options[:clean],
            skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution],
            output_style: 'raw',
            skip_build: true
        )
    end

end